package ai.devchat.devchat

object DevChatActions {
    const val SEND_MESSAGE_REQUEST = "sendMessage/request"
    const val SEND_MESSAGE_RESPONSE = "sendMessage/response"
    const val SET_OR_UPDATE_KEY_REQUEST = "setOrUpdateKey/request"
    const val SET_OR_UPDATE_KEY_RESPONSE = "setOrUpdateKey/response"
    const val ADD_CONTEXT_REQUEST = "addContext/request"
    const val ADD_CONTEXT_RESPONSE = "addContext/response"
    const val ADD_CONTEXT_NOTIFY = "addContext/notify"
    const val LIST_COMMANDS_REQUEST = "listCommands/request"
    const val LIST_COMMANDS_RESPONSE = "listCommands/response"
    const val LOAD_CONVERSATIONS_REQUEST = "loadConversations/request"
    const val LOAD_CONVERSATIONS_RESPONSE = "loadConversations/response"
    const val LOAD_HISTORY_MESSAGES_REQUEST = "loadHistoryMessages/request"
    const val LOAD_HISTORY_MESSAGES_RESPONSE = "loadHistoryMessages/response"
    const val OPEN_LINK_REQUEST = "openLink/request"
    const val OPEN_LINK_RESPONSE = "openLink/response"
    const val LIST_TOPICS_REQUEST = "listTopics/request"
    const val LIST_TOPICS_RESPONSE = "listTopics/response"
    const val INSERT_CODE_REQUEST = "insertCode/request"
    const val INSERT_CODE_RESPONSE = "insertCode/response"
    const val REPLACE_FILE_CONTENT_REQUEST = "replaceFileContent/request"
    const val REPLACE_FILE_CONTENT_RESPONSE = "replaceFileContent/response"
    const val VIEW_DIFF_REQUEST = "viewDiff/request"
    const val VIEW_DIFF_RESPONSE = "viewDiff/response"
    const val LIST_CONTEXTS_REQUEST = "listContexts/request"
    const val LIST_CONTEXTS_RESPONSE = "listContexts/response"
    const val LIST_MODELS_REQUEST = "listModels/request"
    const val LIST_MODELS_RESPONSE = "listModels/response"
    const val GET_KEY_REQUEST = "getKey/request"
    const val GET_KEY_RESPONSE = "getKey/response"
    const val COMMIT_CODE_REQUEST = "commitCode/request"
    const val COMMIT_CODE_RESPONSE = "commitCode/response"
    const val GET_SETTING_REQUEST = "getSetting/request"
    const val GET_SETTING_RESPONSE = "getSetting/response"
    const val UPDATE_SETTING_REQUEST = "updateSetting/request"
    const val UPDATE_SETTING_RESPONSE = "updateSetting/response"
    const val SHOW_SETTING_DIALOG_REQUEST = "showSettingDialog/request"
    const val DELETE_LAST_CONVERSATION_REQUEST = "deleteLastConversation/request"
    const val DELETE_LAST_CONVERSATION_RESPONSE = "deleteLastConversation/response"
    const val DELETE_TOPIC_REQUEST = "deleteTopic/request"
    const val DELETE_TOPIC_RESPONSE = "deleteTopic/response"
}
